version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: next_frontend
    ports:
      - "3000:3000"