services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - webnet

  flask_api:
    build: ./api
    container_name: flask_api
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://user:user_password@mysql_db/mydb
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5001:5000"
    volumes:
      - ./api:/app
    depends_on:
      - mysql_db
    networks:
      - webnet

  frontend:
    build: ./frontend
    container_name: next_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src

networks:
  webnet: