# Usa una imagen base oficial de Python
FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    libcairo2 \
    libpango1.0-0 \
    libffi-dev \
    libgdk-pixbuf2.0-0 \
    libglib2.0-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo requirements.txt y luego instálalo
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación
COPY . .

# Establece la variable de entorno para Flask
ENV FLASK_APP=app  
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development 

# Expone el puerto de la aplicación
EXPOSE 5000

# Ejecuta la aplicación
CMD ["flask", "run"]
