# Usa una imagen base oficial de Python
FROM python:3.9-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia el archivo requirements.txt y luego instálalo
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código de la aplicación
COPY . .

# Establece la variable de entorno para Flask
ENV FLASK_APP=app  
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development 

# Expone el puerto de la aplicación
EXPOSE 5000

# Ejecuta la aplicación
CMD ["flask", "run"]
